// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Q53-_9bi1jBQ40QA5LKyhYoc8yPKuuM',
    appId: '1:27597155714:web:f1029f30bba9f93458f39b',
    messagingSenderId: '27597155714',
    projectId: 'irrigo-3d24f',
    authDomain: 'irrigo-3d24f.firebaseapp.com',
    storageBucket: 'irrigo-3d24f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANj4u7CCuZSZ0m-nzj1AcoegPM9q0qUcI',
    appId: '1:27597155714:android:20fb8000473b469158f39b',
    messagingSenderId: '27597155714',
    projectId: 'irrigo-3d24f',
    storageBucket: 'irrigo-3d24f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpEH2Rwbv1HZ7kg7npGRnnHzUJx7AaQS4',
    appId: '1:27597155714:ios:dfdbb8b685f7e9f658f39b',
    messagingSenderId: '27597155714',
    projectId: 'irrigo-3d24f',
    storageBucket: 'irrigo-3d24f.firebasestorage.app',
    iosBundleId: 'com.example.irrigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpEH2Rwbv1HZ7kg7npGRnnHzUJx7AaQS4',
    appId: '1:27597155714:ios:dfdbb8b685f7e9f658f39b',
    messagingSenderId: '27597155714',
    projectId: 'irrigo-3d24f',
    storageBucket: 'irrigo-3d24f.firebasestorage.app',
    iosBundleId: 'com.example.irrigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Q53-_9bi1jBQ40QA5LKyhYoc8yPKuuM',
    appId: '1:27597155714:web:d20f32116c1231ae58f39b',
    messagingSenderId: '27597155714',
    projectId: 'irrigo-3d24f',
    authDomain: 'irrigo-3d24f.firebaseapp.com',
    storageBucket: 'irrigo-3d24f.firebasestorage.app',
  );
}
